FROM python:3.12-slim

WORKDIR /app

COPY . /app

#requirements.txt should be in the same level of other folders
## keep docker size small and avoid unexpected settings
RUN pip install --no-cache-dir -r requirements.txt

## streamlit's default port
EXPOSE 8501 

ENTRYPOINT ["streamlit", "run", "streamlit/app.py", "--server.port=8501", "--server.address=0.0.0.0"]



